[program:reverb]
command=php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=8081 --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/reverb.log
