services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./storage:/app/storage # Монтуємо локальну папку для перевірки SQLite
    environment:
      - DB_CONNECTION=sqlite